---
- hosts: localhost
  connection: local
  gather_facts: no
  sudo: no
  tasks: 
    - name: Add brew repository
      shell: 'brew tap {{item}}'
      ignore_errors: true
      with_items:
      - "caskroom/cask"
      - "caskroom/versions"
      - "homebrew/binary"

    - name: install homebrew cask
      command: brew install caskroom/cask/brew-cask

    - name: Install development tools
      shell: 'brew install {{item}}'
      ignore_errors: true
      with_items:
      - rbenv
      - ruby-build
      - vim
      - tmux
      - reattach-to-user-namespace
      - tig

    - name: Install homebrew casks
      shell: 'brew cask install {{item}}'
      ignore_errors: true
      with_items:
        - java
        - dropbox
        - virtualbox
        - vagrant
        - karabiner
        - dash
        - google-chrome
        - coteditor
        - google-japanese-ime
        - alfred
        - karabiner
        - virtualbox
        - vagrant
        - firefoxdeveloperedition
        - hipchat
        - sequel-pro

    - name: mkdir vim-neobundle dir
      file: path=~/.vim/bundle state=directory
      notify: install neobundle
