---
- name: update homebrew packages
  community.general.homebrew:
    update_homebrew: true

- name: upgrade homebrew
  community.general.homebrew:
    upgrade_all: true

- name: install homebrew packages
  community.general.homebrew:
    name:
      - asdf
      - git
      - hugo
      - jq
      - mas
      - neovim
      - tig
      - tmux
      - zsh
      - zsh-completions

- name: install homebrew cask packages
  community.general.homebrew_cask:
    name:
      - font-hackgen
      - font-hackgen-nerd
