---
- name: install check oh-my-zsh
  stat:
    path: $HOME/.oh-my-zsh
  register: oh_my_zsh
  
- name: install oh-my-zsh
  ansible.builtin.shell: |
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    executable: /bin/bash
  when: oh_my_zsh.stat.exists == false

- name: install vscode extensions
  ansible.builtin.shell: |
    exts=(
      "eamodio.gitlens"
      "dracula-theme.theme-dracula"
      "Dart-Code.flutter"
      "DEVSENSE.phptools-vscode"
      "Shopify.ruby-lsp"
      "asvetliakov.vscode-neovim"
    )
    cmd="code"
    for ext in "${exts[@]}"; do
      cmd="$cmd --install-extension $ext"
    done
    eval $cmd
  args:
    executable: /bin/bash

- name: check asdf plugins
  ansible.builtin.shell: asdf plugin list
  register: asdf

- name: install asdf plugin dart
  ansible.builtin.shell: asdf plugin add dart
  when: asdf.stdout_lines | regex_search(regex, multiline=True) is not none == false
  vars:
    regex: "dart"

- name: install asdf plugin flutter
  ansible.builtin.shell: asdf plugin add flutter
  when: asdf.stdout_lines | regex_search(regex, multiline=True) is not none == false
  vars:
    regex: "flutter"

- name: install asdf plugin ruby
  ansible.builtin.shell: asdf plugin add ruby
  when: asdf.stdout_lines | regex_search(regex, multiline=True) is not none == false
  vars:
    regex: "ruby"

- name: install asdf plugin php
  ansible.builtin.shell: asdf plugin add php
  when: asdf.stdout_lines | regex_search(regex, multiline=True) is not none == false
  vars:
    regex: "php"

